<a href="https://colab.research.google.com/github/nurahsanadzim/imdb-recommender-system/blob/main/imdb_recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

movie_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/title.basics.tsv', sep='\t')
rating_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/title.ratings.tsv', sep='\t')

In [2]:
rating_df.head()

tconst  averageRating  numVotes
0  tt0000001            5.6      1608
1  tt0000002            6.0       197
2  tt0000003            6.5      1285
3  tt0000004            6.1       121
4  tt0000005            6.1      2050

In [3]:
movie_df.head()

tconst  titleType  ... runtimeMinutes             genres
0  tt0221078      short  ...             \N  Documentary,Short
1  tt8862466  tvEpisode  ...             \N       Comedy,Drama
2  tt7157720  tvEpisode  ...             29   Comedy,Game-Show
3  tt2974998  tvEpisode  ...             \N               News
4  tt2903620  tvEpisode  ...             \N        Documentary

[5 rows x 9 columns]

In [4]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9025 entries, 0 to 9024
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   tconst          9025 non-null   object
 1   titleType       9025 non-null   object
 2   primaryTitle    9011 non-null   object
 3   originalTitle   9011 non-null   object
 4   isAdult         9025 non-null   int64 
 5   startYear       9025 non-null   object
 6   endYear         9025 non-null   object
 7   runtimeMinutes  9025 non-null   object
 8   genres          9014 non-null   object
dtypes: int64(1), object(8)
memory usage: 634.7+ KB


In [5]:
movie_df.isnull().sum()

tconst             0
titleType          0
primaryTitle      14
originalTitle     14
isAdult            0
startYear          0
endYear            0
runtimeMinutes     0
genres            11
dtype: int64

In [6]:
movie_df.loc[(movie_df['primaryTitle'].isnull()) | (movie_df['originalTitle'].isnull())]

tconst  titleType  ... runtimeMinutes                genres
9000  tt10790040  tvEpisode  ...             \N                    \N
9001  tt10891902  tvEpisode  ...             \N                 Crime
9002  tt11737860  tvEpisode  ...             \N  Comedy,Drama,Romance
9003  tt11737862  tvEpisode  ...             \N  Comedy,Drama,Romance
9004  tt11737866  tvEpisode  ...             \N  Comedy,Drama,Romance
9005  tt11737872  tvEpisode  ...             \N                    \N
9006  tt11737874  tvEpisode  ...             \N  Comedy,Drama,Romance
9007   tt1971246  tvEpisode  ...             \N             Biography
9008   tt2067043  tvEpisode  ...             \N                 Music
9009   tt4404732  tvEpisode  ...             \N                Comedy
9010   tt5773048  tvEpisode  ...             \N             Talk-Show
9011   tt8473688  tvEpisode  ...             \N                 Drama
9012   tt8541336  tvEpisode  ...             \N    Reality-TV,Romance
9013   tt9824302  tvEpisode  ...             \N           Documentary

[14 rows x 9 columns]

In [7]:
len(movie_df)

9025

In [8]:
movie_df = movie_df.loc[(movie_df['primaryTitle'].notnull()) & (movie_df['originalTitle'].notnull())]
len(movie_df)

9011

In [9]:
movie_df.loc[movie_df['genres'].isnull()]

tconst  titleType  ...          runtimeMinutes genres
9014  tt10233364  tvEpisode  ...              Reality-TV    NaN
9015  tt10925142  tvEpisode  ...               Talk-Show    NaN
9016  tt10970874  tvEpisode  ...                      \N    NaN
9017  tt11670006  tvEpisode  ...             Documentary    NaN
9018  tt11868642  tvEpisode  ...               Talk-Show    NaN
9019   tt2347742  tvEpisode  ...                      \N    NaN
9020   tt3984412  tvEpisode  ...              Reality-TV    NaN
9021   tt8740950  tvEpisode  ...              Reality-TV    NaN
9022   tt9822816  tvEpisode  ...                      \N    NaN
9023   tt9900062  tvEpisode  ...  Animation,Comedy,Drama    NaN
9024   tt9909210  tvEpisode  ...                      \N    NaN

[11 rows x 9 columns]

In [10]:
movie_df = movie_df.loc[movie_df['genres'].notnull()]
len(movie_df)

9000

In [11]:
movie_df['startYear'] = movie_df['startYear'].replace('\\N', np.nan)
movie_df['startYear'] = movie_df['startYear'].astype('float64')
movie_df['startYear'].unique()[:5]

array([1898., 2018., 2016., 1987., 1973.])

In [12]:
movie_df['endYear'] = movie_df['endYear'].replace('\\N', np.nan)
movie_df['endYear'] = movie_df['endYear'].astype('float64')
movie_df['endYear'].unique()[:5]

array([  nan, 2005., 1955., 2006., 1999.])

In [13]:
movie_df['runtimeMinutes'] = movie_df['runtimeMinutes'].replace('\\N', np.nan)
movie_df['runtimeMinutes'] = movie_df['runtimeMinutes'].astype('float64')
movie_df['runtimeMinutes'].unique()[:5]

array([nan, 29.,  7., 23., 85.])

In [14]:
def transform_to_list(x):
    if ',' in x: 
        return x.split(',')
    else: 
        return []

In [15]:
movie_df['genres'] = movie_df['genres'].apply(lambda x: transform_to_list(x))

In [16]:
movie_df['genres'].head()

0    [Documentary, Short]
1         [Comedy, Drama]
2     [Comedy, Game-Show]
3                      []
4                      []
Name: genres, dtype: object

In [17]:
rating_df.head()

tconst  averageRating  numVotes
0  tt0000001            5.6      1608
1  tt0000002            6.0       197
2  tt0000003            6.5      1285
3  tt0000004            6.1       121
4  tt0000005            6.1      2050

In [18]:
rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030009 entries, 0 to 1030008
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype  
---  ------         --------------    -----  
 0   tconst         1030009 non-null  object 
 1   averageRating  1030009 non-null  float64
 2   numVotes       1030009 non-null  int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 23.6+ MB


In [20]:
# Lakukan join pada kedua table
movie_rating_df = pd.merge(movie_df, rating_df, on='tconst', how='inner')

print(movie_rating_df.head())
print(movie_rating_df.info())

      tconst  titleType  ... averageRating numVotes
0  tt0043745      short  ...           7.1      459
1  tt0167491      video  ...           5.7        7
2  tt6574096  tvEpisode  ...           8.5      240
3  tt6941700  tvEpisode  ...           8.0       11
4  tt7305674      video  ...           9.7        7

[5 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1376 entries, 0 to 1375
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   tconst          1376 non-null   object 
 1   titleType       1376 non-null   object 
 2   primaryTitle    1376 non-null   object 
 3   originalTitle   1376 non-null   object 
 4   isAdult         1376 non-null   int64  
 5   startYear       1376 non-null   float64
 6   endYear         26 non-null     float64
 7   runtimeMinutes  1004 non-null   float64
 8   genres          1376 non-null   object 
 9   averageRating   1376 non-null   float64
 10  numVotes     

In [21]:
movie_rating_df = movie_rating_df.dropna(subset=['startYear','runtimeMinutes'])

# Untuk memastikan tidak ada lagi nilai NULL
movie_rating_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1004 entries, 0 to 1374
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   tconst          1004 non-null   object 
 1   titleType       1004 non-null   object 
 2   primaryTitle    1004 non-null   object 
 3   originalTitle   1004 non-null   object 
 4   isAdult         1004 non-null   int64  
 5   startYear       1004 non-null   float64
 6   endYear         17 non-null     float64
 7   runtimeMinutes  1004 non-null   float64
 8   genres          1004 non-null   object 
 9   averageRating   1004 non-null   float64
 10  numVotes        1004 non-null   int64  
dtypes: float64(4), int64(2), object(5)
memory usage: 94.1+ KB


In [24]:
C = movie_rating_df['averageRating'].mean()

In [25]:
m = movie_rating_df['numVotes'].quantile(0.8)

In [26]:
def imdb_weighted_rating(df, var=0.8):
    v = df['numVotes']
    R = df['averageRating']
    C = df['averageRating'].mean()
    m = df['numVotes'].quantile(var)
    df['score'] = (v/(m+v))*R + (m/(m+v))*C # rumus IMDb 
    return df['score']
    
imdb_weighted_rating(movie_rating_df)

# melakukan pengecekan dataframe
print(movie_rating_df.head())

      tconst  titleType  ... numVotes     score
0  tt0043745      short  ...      459  7.009992
1  tt0167491      video  ...        7  6.796077
2  tt6574096  tvEpisode  ...      240  7.684380
5  tt2262289      movie  ...       27  6.921384
6  tt0874027  tvEpisode  ...        8  6.869089

[5 rows x 12 columns]


In [27]:
def simple_recommender(df, top=100):
    df = df.loc[df['numVotes'] >= m]
    df = df.sort_values(by='score',ascending=False) #urutkan dari nilai tertinggi ke terendah
    
    df = df[:top]
    return df
      
print(simple_recommender(movie_rating_df, top=25))

         tconst  titleType  ... numVotes     score
68    tt4110822  tvEpisode  ...     3820  9.254624
236   tt2200252      video  ...     1411  8.955045
1181  tt7697962  tvEpisode  ...     1536  8.892450
326   tt7124590  tvEpisode  ...     1859  8.850993
1045  tt0533506  tvEpisode  ...     2740  8.740308
71    tt8399426  tvEpisode  ...     1428  8.700045
1234  tt2843830  tvEpisode  ...     1753  8.660784
1087  tt4295140   tvSeries  ...    12056  8.566998
1054  tt2503932  tvEpisode  ...     2495  8.451165
448   tt0337566      video  ...     1343  8.256663
624   tt0620159  tvEpisode  ...      401  8.020118
1281  tt3166390  tvEpisode  ...      396  8.014679
314   tt0954759  tvEpisode  ...     2766  8.002863
189   tt5661506      video  ...      330  7.992798
151   tt3954426  tvEpisode  ...      437  7.991253
1344  tt6644294  tvEpisode  ...      812  7.976536
1242  tt3677742  tvSpecial  ...     1931  7.965312
1217  tt3642464  tvEpisode  ...      566  7.947641
544   tt0734655  tvEpisode  ...

In [30]:
df = movie_rating_df.copy()

def user_prefer_recommender(df, ask_adult, ask_start_year, ask_genre, top=100):
    #ask_adult = yes/no
    if ask_adult.lower() == 'yes':
        df = df.loc[df['isAdult'] == 1]
    elif ask_adult.lower() == 'no':
        df = df.loc[df['isAdult'] == 0]

    df = df.loc[df['startYear'] >= int(ask_start_year)]

    # ask_genre = 'all' atau yang lain
    if ask_genre.lower() == 'all':
        df = df = df.loc[df['startYear'] >= int(ask_start_year)]
    else:
        def filter_genre(x):
            if ask_genre.lower() in str(x).lower():
                return True
            else:
                return False
        df = df.loc[df['genres'].apply(lambda x: filter_genre(x))]

    # Mengambil film dengan m yang lebih besar dibanding numVotes
    df = df.loc[df['numVotes'] >= m ]
    df = df.sort_values(by='score', ascending=False)
    
    df = df[:top]
    return df

print(user_prefer_recommender(df, ask_adult = 'no', ask_start_year = 2000, ask_genre = 'drama'))

          tconst  titleType  ... numVotes     score
1368  tt11143130  tvEpisode  ...      132  7.842588
1072   tt1285093  tvEpisode  ...      173  7.548443
377    tt5502778  tvEpisode  ...      144  7.513068
593    tt0629586  tvEpisode  ...      217  7.496355
89     tt8528008  tvEpisode  ...      126  7.457956
...          ...        ...  ...      ...       ...
270    tt4535672      short  ...       14  6.804832
812   tt11422924      movie  ...        5  6.803309
478    tt2871088      short  ...        8  6.801579
345    tt2076213      short  ...       35  6.799145
269    tt2145676      movie  ...       19  6.796670

[100 rows x 12 columns]
